---
title: "ag_census_2017_exploration"
output: html_document
---

```{r}

library(dplyr)

here::i_am("R/ag_census_2017_exploration.Rmd")

```

```{r}

dta <- readr::read_csv(here::here("data/2017_cdqt_data.csv"))

dta_ia <- dta %>%
  filter(STATE_ALPHA == "IA") %>%
  filter(AGG_LEVEL_DESC == "COUNTY")

```


```{r}

# Calculate and double check national cover crop aces and percentages

# National cover crops
dta_natl_cc <- dta %>%
  filter(AGG_LEVEL_DESC == "NATIONAL") %>%
  filter(SHORT_DESC == "PRACTICES, LAND USE, CROPLAND, COVER CROP PLANTED, (EXCL CRP) - ACRES") %>%
  filter(stringr::str_starts(DOMAINCAT_DESC, "AREA O")) %>%
  mutate(
    value = as.numeric(gsub(",", "", VALUE))
  )

natl_cc_sum <- sum(dta_natl_cc$value, na.rm = TRUE)

# Calculate harvested cropland minus alfalfa
natl_hc_sum  <- dta %>%
  filter(SECTOR_DESC == "ECONOMICS") %>%
  filter(SHORT_DESC == "AG LAND, CROPLAND, HARVESTED - ACRES") %>%
  filter(AGG_LEVEL_DESC == "NATIONAL") %>%
  filter(CENSUS_CHAPTER == "1") %>%
  filter(CENSUS_TABLE == "1") %>%
  filter(CENSUS_ROW == "18") %>%
  filter(CENSUS_COLUMN == "1") %>%
  mutate(
    value = as.numeric(gsub(",", "", VALUE))
  ) %>%
  pull(value) %>%
  sum(na.rm = TRUE)
  
  

alfalfa_crops <- c(
  "HAY, ALFALFA - ACRES HARVESTED",
  "HAYLAGE, ALFALFA - ACRES HARVESTED"
)

natl_alfalfa_sum <- dta %>%
  filter(AGG_LEVEL_DESC == "NATIONAL") %>%
  filter(SECTOR_DESC == "CROPS") %>%
  filter(stringr::str_starts(DOMAINCAT_DESC, "AREA O")) %>%
  filter(stringr::str_detect(SHORT_DESC, "ACRES HARVESTED")) %>%
mutate(
  value = as.numeric(gsub(",", "", VALUE))
) %>%
  filter(SHORT_DESC %in% alfalfa_crops) %>%
  pull(value) %>%
  sum(na.rm = TRUE)


(natl_cc_sum / (natl_hc_sum - natl_alfalfa_sum)) * 100

```


```{r}

# Calculate total crop cover use
dta_cc_tot <- dta %>%
  filter(STATE_ALPHA == "TN") %>%
  filter(AGG_LEVEL_DESC == "COUNTY") %>%
  filter(SHORT_DESC == "PRACTICES, LAND USE, CROPLAND, COVER CROP PLANTED, (EXCL CRP) - ACRES") %>%
  mutate(
    value = as.numeric(gsub(",", "", VALUE))
  )


alfalfa_crops <- c(
  "HAY, ALFALFA - ACRES HARVESTED",
  "HAYLAGE, ALFALFA - ACRES HARVESTED"
)

tn_total <- dta %>%
  filter(STATE_ALPHA == "TN") %>%
  filter(AGG_LEVEL_DESC == "COUNTY") %>%
  filter(SECTOR_DESC == "CROPS") %>%
  filter(stringr::str_detect(SHORT_DESC, "ACRE")) %>%
  mutate(
    value = as.numeric(gsub(",", "", VALUE))
  ) %>%
  filter(!SHORT_DESC %in% alfalfa_crops)
  
sum_cc <- dta_cc_tot %>%
  pull(value) %>%
  sum(na.rm = TRUE)

```


