---
title: "dot_density_ia_current_crop_coverage"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(cartogram)
library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/dot_density_ia_current_crop_coverage.Rmd")

source(here::here("R/utils.R"))

```


```{r}

dta <- readr::read_csv(here::here("data/ia_crop_calculations.csv")) %>%
  mutate(
    geoid_co = stringr::str_pad(geoid_co, 5, side = "left", pad = "0")
  )

```


```{r}

ia_counties <- tigris::counties(state = "IA", cb = TRUE, year = 2021)

```


```{r}

dots <- dta %>%
  select(
    geoid_co,
    corn_grain_acres_harvested,
    wheat_acres_harvested,
    oats_acres_harvested,
    soybeans_acres_harvested,
    rye_acres_harvested,
    cover_crop_acres_planted
  ) %>%
  tidyr::pivot_longer(!geoid_co) %>%
  filter(!is.na(value)) %>%
  filter(value > 0) %>%
  left_join(
    .,
    ia_counties,
    by = c("geoid_co" = "GEOID")
  ) %>%
  sf::st_as_sf() %>%
  tidycensus::as_dot_density(
    value = "value",
    values_per_dot = 100,
    group = "name"
  ) %>%
  arrange(sample(n()))
  

```


```{r}

color_scale <- c(
  "corn_grain_acres_harvested" = "#964B00",
  "wheat_acres_harvested" = "#00835D",
  "oats_acres_harvested" = "#00835D",
  "soybeans_acres_harvested" = "#964B00",
  "rye_acres_harvested" = "#00835D",
  "cover_crop_acres_planted" = "#00835D"
)

fig <- dta %>%
  ggplot() +
  geom_sf(data = ia_counties, fill = NA, linewidth = 0.5, color = "#d0d2ce") +
  geom_sf(data = dots, aes(color = name), size = .0001, alpha = .4) +
  scale_color_manual(values = color_scale) +
  theme_cori_map() +
  guides(
    color = guide_legend(override.aes = list(size = 4, alpha = 1))
  )

save_plot(fig, here::here("export/dot_density_curr_crop_coverage.png"), chart_height = 8)

```
