---
title: "ia_crop_data_summary"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)

here::i_am("R/ia_crop_data_summary.Rmd")
source(here::here("R/utils.R"))

```

```{r}

dta_ia <- readr::read_csv(here::here("data/2017_agcensus_ia_co.csv"))

```

```{r}

crop_desc <- c(
  # Harvest cropland variables
  "AG LAND, CROPLAND, HARVESTED - ACRES",
  "HAY, ALFALFA - ACRES HARVESTED",
  "HAYLAGE, ALFALFA - ACRES HARVESTED",
  # corn, soy, and small grains (oats, rye, wheat)
  "CORN, GRAIN - ACRES HARVESTED",
  "SOYBEANS - ACRES HARVESTED",
  "OATS - ACRES HARVESTED",
  "RYE - ACRES HARVESTED",
  "WHEAT - ACRES HARVESTED",
  # Cover crop acreage
  "PRACTICES, LAND USE, CROPLAND, COVER CROP PLANTED, (EXCL CRP) - ACRES"
)

dta <- dta_ia %>%
  filter(SHORT_DESC %in% crop_desc) %>%
  filter(is.na(DOMAINCAT_DESC)) %>%
  select(-c("CENSUS_CHAPTER", "CENSUS_TABLE", "CENSUS_ROW", "CENSUS_COLUMN",
            "COMMODITY_DESC", "SECTOR_DESC", "DOMAINCAT_DESC")) %>%
  distinct() %>%
  mutate(
    SHORT_DESC = case_match(
      SHORT_DESC,
      "AG LAND, CROPLAND, HARVESTED - ACRES" ~ "cropland_acres_harvested",
      "HAY, ALFALFA - ACRES HARVESTED" ~ "hay_alfalfa_acres_harvested",
      "HAYLAGE, ALFALFA - ACRES HARVESTED" ~ "haylage_alfalfa_acres_harvested",
      "CORN, GRAIN - ACRES HARVESTED" ~ "corn_grain_acres_harvested",
      "SOYBEANS - ACRES HARVESTED" ~ "soybeans_acres_harvested",
      "OATS - ACRES HARVESTED" ~ "oats_acres_harvested",
      "RYE - ACRES HARVESTED" ~ "rye_acres_harvested",
      "WHEAT - ACRES HARVESTED" ~ "wheat_acres_harvested",
      "PRACTICES, LAND USE, CROPLAND, COVER CROP PLANTED, (EXCL CRP) - ACRES" ~ "cover_crop_acres_planted"
    ),
    VALUE = ifelse(
      is.na(as.numeric(gsub(",", "", VALUE))), 
      0,
      as.numeric(gsub(",", "", VALUE))
    )
  ) %>%
  filter(!is.na(VALUE)) %>%
  tidyr::pivot_wider(
    names_from = "SHORT_DESC",
    values_from = "VALUE"
  ) %>%
  tidyr::replace_na(
    list(
      cropland_acres_harvested = 0,
      hay_alfalfa_acres_harvested = 0,
      haylage_alfalfa_acres_harvested = 0,
      corn_grain_acres_harvested = 0,
      soybeans_acres_harvested = 0,
      oats_acres_harvested = 0,
      rye_acres_harvested = 0,
      wheat_acres_harvested = 0,
      cover_crop_acres_planted = 0
    )
  ) %>%
  mutate(
    # Denominator calculations
    haylage_alfalfa_acres_harvested = tidyr::replace_na(haylage_alfalfa_acres_harvested, 0),
    viable_cropland = cropland_acres_harvested - hay_alfalfa_acres_harvested - haylage_alfalfa_acres_harvested,
    # Calculate crop coverage
    pct_corn_grain_acres = corn_grain_acres_harvested / viable_cropland,
    pct_soybeans_acres = soybeans_acres_harvested / viable_cropland,
    pct_oats_acres = oats_acres_harvested / viable_cropland,
    pct_rye_acres = rye_acres_harvested / viable_cropland,
    pct_wheat_acres = wheat_acres_harvested / viable_cropland,
    pct_cover_crop = cover_crop_acres_planted / viable_cropland,
    # GEOID
    geoid_co = paste0(STATE_FIPS_CODE, COUNTY_CODE)
  )

# Export data
readr::write_csv(dta, here::here("data/ia_crop_calculations.csv"))

```

```{r}

# Convert the tibble to a data frame and calculate column sums
acreage_counts <- dta %>%
  select(tidyr::contains("acres_harvested") | tidyr::contains("acres_planted") | tidyr::contains("viable")) %>%
  summarise(
    corn_grain_acres_harvested = sum(corn_grain_acres_harvested, na.rm = TRUE),
    wheat_acres_harvested = sum(wheat_acres_harvested, na.rm = TRUE),
    oats_acres_harvested = sum(oats_acres_harvested, na.rm = TRUE),
    soybeans_acres_harvested = sum(soybeans_acres_harvested, na.rm = TRUE),
    rye_acres_harvested = sum(rye_acres_harvested, na.rm = TRUE),
    cover_crop_acres_planted = sum(cover_crop_acres_planted, na.rm = TRUE),
    viable_cropland = sum(viable_cropland, na.rm = TRUE),
    cropland_acres_harvested = sum(cropland_acres_harvested, na.rm = TRUE)
  )

```
