---
title: "map_ia_cover_crop_use"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(cartogram)
library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/map_ia_cover_crop_use.Rmd")

source(here::here("R/utils.R"))

```


```{r}

dta_ia <- readr::read_csv(here::here("data/2017_agcensus_ia_co.csv"))

```

```{r}

# Filter to the appropriate rows
cc_desc <- c(
  "PRACTICES, LAND USE, CROPLAND, COVER CROP PLANTED, (EXCL CRP) - ACRES",
  "AG LAND, CROPLAND, HARVESTED - ACRES",
  "HAY, ALFALFA - ACRES HARVESTED",
  "HAYLAGE, ALFALFA - ACRES HARVESTED"
)


dta <- dta_ia %>%
  filter(SHORT_DESC %in% cc_desc) %>%
  filter(is.na(DOMAINCAT_DESC)) %>%
  select(-c("CENSUS_CHAPTER", "CENSUS_TABLE", "CENSUS_ROW", "CENSUS_COLUMN",
            "COMMODITY_DESC", "SECTOR_DESC")) %>%
  distinct() %>%
  mutate(
    SHORT_DESC = case_match(
      SHORT_DESC,
      "AG LAND, CROPLAND, HARVESTED - ACRES" ~ "cropland_acres_harvested",
      "HAY, ALFALFA - ACRES HARVESTED" ~ "hay_alfalfa_acres_harvested",
      "HAYLAGE, ALFALFA - ACRES HARVESTED" ~ "haylage_alfalfa_acres_harvested",
      "PRACTICES, LAND USE, CROPLAND, COVER CROP PLANTED, (EXCL CRP) - ACRES" ~ "cover_crop_acres_planted"
    ),
    VALUE = as.numeric(gsub(",", "", VALUE))
  ) %>%
  tidyr::pivot_wider(
    names_from = "SHORT_DESC",
    values_from = "VALUE"
  ) %>%
  mutate(
    haylage_alfalfa_acres_harvested = tidyr::replace_na(haylage_alfalfa_acres_harvested, 0),
    viable_cropland = cropland_acres_harvested - hay_alfalfa_acres_harvested - haylage_alfalfa_acres_harvested,
    pct_cover_crop = cover_crop_acres_planted / viable_cropland,
    geoid_co = paste0(STATE_FIPS_CODE, COUNTY_CODE)
  )

# Export data
# readr::write_csv(dta, here::here("data/ia_cover_crop_calculations.csv"))

```

```{r}

# get Iowa geometries
ia_counties <- tigris::counties(state = "IA", cb = TRUE, year = 2021)
  
dta_sf <- left_join(
    dta,
    ia_counties,
    by = c("geoid_co" = "GEOID")
  ) %>%
  sf::st_as_sf()

```

```{r}

# fig <- dta_sf %>%
#   ggplot() +
#   geom_sf(aes(fill = pct_cover_crop), color = "black") +
#   scale_fill_gradient2(
#     low = "#F2FBEC", 
#     mid = "#65ACA5",
#     midpoint = .06,
#     high = "#061E46",
#     limits = c(0, NA),
#     labels = scales::percent_format(scale = 100, accuracy = 1),
#     n.breaks = 6
#   ) +
#   labs(
#     title = "Percent cover crop",
#     subtitle = "Share of harvested cropland acres",
#     x = NULL,
#     y = NULL,
#     caption = "Source: 2017 Census of Agriculture"
#   ) +
#   theme_cori_map() +
#   theme(
#     legend.key.width = unit(50, "pt")
#   )

fig <- get_ia_choropleth(dta_sf, "pct_cover_crop") +
  labs(
    title = "Percent cover crops",
    subtitle = "Share of total harvested cropland, excluding harvested alfalfa acreage",
    x = NULL,
    y = NULL,
    caption = "Source: 2017 Census of Agriculture"
  )

file_path <- paste0("export/ia_cover_crops.png")
save_plot(fig, here::here(file_path), chart_height = 7.5)

```


```{r}

# dta_cartogram <- dta_sf %>%
#   sf::st_transform(crs = 3857) %>%
#   cartogram_dorling(weight = "cover_crop_acres_planted", k = 1)

# dta_cartogram <- sf::st_centroid(dta_sf)
# 
# fig <- dta_cartogram %>%
#   ggplot() +
#   geom_sf(data = ia_counties, fill = NA, linewidth = 0.5, color = "#d0d2ce") +
#   geom_sf(aes(color = pct_cover_crop, size = cover_crop_acres_planted)) +
#   scale_size_continuous(
#     range = c(0, 9),
#     labels = scales::number_format(scale_cut = scales::cut_short_scale())
#   ) +
#   scale_color_gradient2(
#     low = "#F2FBEC", 
#     mid = "#65ACA5",
#     midpoint = .06,
#     high = "#061E46",
#     limits = c(0, NA),
#     labels = scales::percent_format(scale = 100, accuracy = 1),
#     n.breaks = 6
#   ) +
#   labs(
#     title = "Percent cover crop",
#     subtitle = "Share of harvested cropland acres, circles sized by cover crop acreage",
#     x = NULL,
#     y = NULL,
#     caption = "Source: 2017 Census of Agriculture"
#   ) +
#   theme_cori_map() +
#   theme(
#     legend.box = "vertical",
#     legend.key.width = unit(40, "pt")
#   ) +
#   guides(
#     size = guide_legend(
#       keywidth = unit(10, "pt")
#     )
#   )

fig <- get_ia_bubble_map(dta_sf, "pct_cover_crop", "cover_crop_acres_planted") +
  labs(
    title = "Percent cover crops",
    subtitle = "Share of total harvested cropland, excluding harvested alfalfa acreage. Circles sized by total acreage.",
    x = NULL,
    y = NULL,
    caption = "Source: 2017 Census of Agriculture"
  )

file_path <- paste0("export/ia_bubble_cover_crop.png")
save_plot(fig, here::here(file_path), chart_height = 7.5)

```

