---
title: "map_ia_current_crop_coverage"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(cartogram)
library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/map_ia_current_crop_coverage.Rmd")

source(here::here("R/utils.R"))

```

```{r}

params <- yaml::read_yaml(here::here("params.yml"))
dta_ia <- readr::read_csv(here::here("data/2017_agcensus_ia_co.csv"))

```

```{r}

crop_desc <- c(
  # Harvest cropland variables
  "AG LAND, CROPLAND, HARVESTED - ACRES",
  "HAY, ALFALFA - ACRES HARVESTED",
  "HAYLAGE, ALFALFA - ACRES HARVESTED",
  # corn, soy, and small grains (oats, rye, wheat)
  "CORN, GRAIN - ACRES HARVESTED",
  "SOYBEANS - ACRES HARVESTED",
  "OATS - ACRES HARVESTED",
  "RYE - ACRES HARVESTED",
  "WHEAT - ACRES HARVESTED",
  # Hog info
  "HOGS - INVENTORY"
)

dta <- dta_ia %>%
  filter(SHORT_DESC %in% crop_desc) %>%
  filter(is.na(DOMAINCAT_DESC)) %>%
  select(-c("CENSUS_CHAPTER", "CENSUS_TABLE", "CENSUS_ROW", "CENSUS_COLUMN",
            "COMMODITY_DESC", "SECTOR_DESC")) %>%
  distinct() %>%
  mutate(
    SHORT_DESC = case_match(
      SHORT_DESC,
      "AG LAND, CROPLAND, HARVESTED - ACRES" ~ "cropland_acres_harvested",
      "HAY, ALFALFA - ACRES HARVESTED" ~ "hay_alfalfa_acres_harvested",
      "HAYLAGE, ALFALFA - ACRES HARVESTED" ~ "haylage_alfalfa_acres_harvested",
      "CORN, GRAIN - ACRES HARVESTED" ~ "corn_grain_acres_harvested",
      "SOYBEANS - ACRES HARVESTED" ~ "soybeans_acres_harvested",
      "OATS - ACRES HARVESTED" ~ "oats_acres_harvested",
      "RYE - ACRES HARVESTED" ~ "rye_acres_harvested",
      "WHEAT - ACRES HARVESTED" ~ "wheat_acres_harvested",
      "HOGS - INVENTORY" ~ "hog_head"
    ),
    VALUE = ifelse(
      is.na(as.numeric(gsub(",", "", VALUE))), 
      0,
      as.numeric(gsub(",", "", VALUE))
    )
  ) %>%
  filter(!is.na(VALUE)) %>%
  tidyr::pivot_wider(
    names_from = "SHORT_DESC",
    values_from = "VALUE"
  ) %>%
  tidyr::replace_na(
    list(
      cropland_acres_harvested = 0,
      hay_alfalfa_acres_harvested = 0,
      haylage_alfalfa_acres_harvested = 0,
      corn_grain_acres_harvested = 0,
      soybeans_acres_harvested = 0,
      oats_acres_harvested = 0,
      rye_acres_harvested = 0,
      wheat_acres_harvested = 0,
      hog_head = 0
    )
  ) %>%
  mutate(
    # Denominator calculations
    haylage_alfalfa_acres_harvested = tidyr::replace_na(haylage_alfalfa_acres_harvested, 0),
    viable_cropland = cropland_acres_harvested - hay_alfalfa_acres_harvested - haylage_alfalfa_acres_harvested,
    # Calculate crop coverage
    pct_corn_grain = corn_grain_acres_harvested / viable_cropland,
    pct_soybeans_acres = soybeans_acres_harvested / viable_cropland,
    pct_oats_acres = oats_acres_harvested / viable_cropland,
    pct_rye_acres = rye_acres_harvested / viable_cropland,
    pct_wheat_acres = wheat_acres_harvested / viable_cropland,
    # Hog calculations
    total_hog_head = sum(hog_head, na.rm = TRUE),
    pct_hog_head = hog_head / total_hog_head,
    # GEOID
    geoid_co = paste0(STATE_FIPS_CODE, COUNTY_CODE),
    # GHG emissions,
    co2_corn_grain = corn_grain_acres_harvested * params$co2_per_acre$corn_grain,
    co2_soybeans = soybeans_acres_harvested * params$co2_per_acre$soybeans,
    co2_oats = oats_acres_harvested * params$co2_per_acre$oats,
    co2_rye = ((rye_acres_harvested/2) * params$co2_per_acre$rye_feed) + ((rye_acres_harvested/2) * params$co2_per_acre$rye_seed),
    co2_wheat = wheat_acres_harvested * params$co2_per_acre$wheat
  )

# Export data
readr::write_csv(dta, here::here("data/ia_current_crop_calculations.csv"))

```


```{r}

# get Iowa geometries
ia_counties <- tigris::counties(state = "IA", cb = TRUE, year = 2021)
  
dta_sf <- left_join(
    dta,
    ia_counties,
    by = c("geoid_co" = "GEOID")
  ) %>%
  sf::st_as_sf()

```

```{r}

source(here::here("R/utils.R"))

pct_cols <- dta_sf %>%
  select(tidyr::starts_with("pct_")) %>%
  sf::st_drop_geometry() %>%
  colnames() %>%
  unique()

for (col_name in pct_cols) {
  
  chart_title <- stringr::str_replace(col_name, "pct", "Percent") %>%
    stringr::str_replace_all("_", " ")
  
  fig <- get_ia_choropleth(dta_sf, col_name) +
    labs(
      title = chart_title,
      subtitle = "Share of total harvested cropland, excluding harvested alfalfa acreage",
      x = NULL,
      y = NULL,
      caption = "Source: 2017 Census of Agriculture"
    )
  
  file_path <- paste0("export/ia_", col_name, ".png")
  save_plot(fig, here::here(file_path), chart_height = 7.5)
  
}


```

```{r}

acre_var_dict <- list(
  pct_corn_grain = "corn_grain_acres_harvested",
  pct_soybeans_acres = "soybeans_acres_harvested",
  pct_oats_acres = "oats_acres_harvested",
  pct_rye_acres = "rye_acres_harvested",
  pct_wheat_acres = "wheat_acres_harvested"  
)

for (col_name in pct_cols) {
  
  chart_title <- stringr::str_replace(col_name, "pct", "Percent") %>%
    stringr::str_replace_all("_", " ")
  
  # Get bubble map
  fig <- get_ia_bubble_map(dta_sf, col_name, acre_var_dict[[col_name]]) +
    labs(
      title = chart_title,
      subtitle = "Share of total harvested cropland, excluding harvested alfalfa acreage. Circles sized by total acreage.",
      x = NULL,
      y = NULL,
      caption = "Source: 2017 Census of Agriculture"
    )
  
  file_path <- paste0("export/ia_bubble_", col_name, ".png")
  save_plot(fig, here::here(file_path), chart_height = 8)
  
}

```




