---
title: "scenario_a_calculations"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(yaml)

here::i_am("R/scenario_a_calculations.Rmd")
source(here::here("R/utils.R"))

```


```{r}

params <- yaml::read_yaml(here::here("params.yml"))

dta <- readr::read_csv(here::here("data/ia_crop_calculations.csv"))

```


Scenario A: Introduce 1 acre of fall cover crop for every acre of harvested soybeans

```{r}

co2_change_corn_to_lcc <- params$co2_per_acre$low_carbon_corn - params$co2_per_acre$corn_grain

```

```{r}
# lcc = low carbon corn
# cc = cover crop

dta_calc <- dta %>%
  mutate(
    #
    # Determine acre changes
    #
    cc_on_soybean_acres = soybeans_acres_harvested,
    new_rye_acres_for_seed = cc_on_soybean_acres / params$ratios$planted_acres_from_1_acre_rye_seed,
    new_acres_lcc = new_rye_acres_for_seed,
    corn_acres_displaced_by_rye_for_seed = new_rye_acres_for_seed,
    #
    # Calculate carbon changes
    #
    co2_change_cc = cc_on_soybean_acres * params$co2_per_acre$cover_crops,
    co2_change_lcc = new_acres_lcc * co2_change_corn_to_lcc,
    co2_change_rye = new_rye_acres_for_seed * params$co2_per_acre$rye_seed,
    c02_change_corn_removal = corn_acres_displaced_by_rye_for_seed * -params$co2_per_acre$corn_grain,
    co2_net = co2_change_cc + co2_change_lcc + co2_change_rye + c02_change_corn_removal,
    #
    # Calculate new crop composition totals
    #
    corn_grain_acres_harvested = corn_grain_acres_harvested - corn_acres_displaced_by_rye_for_seed - new_acres_lcc,
    rye_acres_harvested = rye_acres_harvested + new_rye_acres_for_seed,
    cover_crop_acres_planted = cover_crop_acres_planted + cc_on_soybean_acres,
    #
    # Calculate outcomes
    #
    increase_lcc_acres = new_acres_lcc,
    extra_acres_covered_per_year = new_rye_acres_for_seed + cc_on_soybean_acres
  )

```


```{r}

dta_calc_ia <- dta_calc %>%
  group_by(STATE_NAME) %>%
  summarise(
    corn_grain_acres_harvested = sum(corn_grain_acres_harvested, na.rm = T),
    rye_acres_harvested = sum(rye_acres_harvested, na.rm = T),
    cover_crop_acres_planted = sum(cover_crop_acres_planted, na.rm = T),
    co2_net = sum(co2_net, na.rm = T),
    increase_lcc_acres = sum(increase_lcc_acres, na.rm = T),
    extra_acres_covered_per_year = sum(extra_acres_covered_per_year, na.rm = T)
  )
  

```



