---
title: "scenario_c_calculations"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(yaml)

here::i_am("R/scenario_c_calculations.Rmd")
source(here::here("R/utils.R"))

```

```{r}

params <- yaml::read_yaml(here::here("params.yml"))
dta <- readr::read_csv(here::here("data/ia_crop_calculations.csv"))

```


```{r}

dta_calc <- dta %>%
  mutate(
    # Calculate acre variables
    acres_converted_to_oats = params$converted_cropland$pct_converted_to_oats * viable_cropland,
    new_lcc_acres = acres_converted_to_oats,
    # Calculate emissions
    co2_change_oats = acres_converted_to_oats * (params$co2_per_acre$oats - params$co2_per_acre$corn_grain),
    co2_change_lcc = new_lcc_acres * (params$co2_per_acre$low_carbon_corn - params$co2_per_acre$corn_grain),
    co2_net = co2_change_lcc + co2_change_oats,
    # Calculate new crop composition
    corn_grain_acres_harvested = corn_grain_acres_harvested - acres_converted_to_oats - new_lcc_acres,
    oats_acres_harvested = oats_acres_harvested + acres_converted_to_oats,
    # Calculate outcomes
    increase_lcc_acres = new_lcc_acres,
    extra_acres_covered_per_year = acres_converted_to_oats
  )

```

```{r}

dta_calc_ia <- dta_calc %>%
  group_by(STATE_NAME) %>%
  summarise(
    cover_crop_acres_planted = 0, # Oats for food is cash crop not cover crop
    co2_net = sum(co2_net, na.rm = T),
    increase_lcc_acres = sum(increase_lcc_acres, na.rm = T),
    extra_acres_covered_per_year = sum(extra_acres_covered_per_year, na.rm = T),
    corn_grain_acres_harvested = sum(corn_grain_acres_harvested, na.rm = T)
  )

```
