---
title: "scenario_b_calculations"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(yaml)

here::i_am("R/scenario_b_calculations.Rmd")
source(here::here("R/utils.R"))

```

```{r}

params <- yaml::read_yaml(here::here("params.yml"))
dta <- readr::read_csv(here::here("data/ia_crop_calculations.csv"))

```

Scenario B: Hog diet changes, increase in Rye consumption


```{r}

# Variable declarations
rye_bushels_per_hog <- params$hog_info$rye_lb_increase_per_hog / params$hog_info$lbs_per_rye_bushel
hybrid_rye_acres_needed = (params$hog_info$number_of_hogs * rye_bushels_per_hog) / params$hog_info$rye_bushels_per_acre
new_acres_lcc = hybrid_rye_acres_needed

# Updated crop values
corn_grain_acres = sum(dta$corn_grain_acres_harvested, na.rm = T) - hybrid_rye_acres_needed - new_acres_lcc

```


```{r}

# Apply these estimates across counties
dta_calc <- dta %>%
  mutate(
    # Calculate new acres by county using corn weighting
    corn_grain_acres_harvested = corn_grain_acres * pct_corn_grain_acres,
    new_acres_lcc = new_acres_lcc * pct_corn_grain_acres,
    new_acres_hybrid_rye = hybrid_rye_acres_needed * pct_corn_grain_acres,
    # Calculate carbon emissions
    co2_change_hybrid_rye = new_acres_hybrid_rye * (params$co2_per_acre$rye_feed - params$co2_per_acre$corn_grain),
    co2_change_lcc = new_acres_lcc * (params$co2_per_acre$low_carbon_corn - params$co2_per_acre$corn_grain),
    co2_net = co2_change_hybrid_rye + co2_change_lcc,
    # Calculate outcomes
    increase_lcc_acres = new_acres_lcc,
    extra_acres_covered_per_year = new_acres_hybrid_rye
  )

```


```{r}

dta_calc_ia <- dta_calc %>%
  group_by(STATE_NAME) %>%
  summarise(
    cover_crop_acres_planted = 0, # Rye for feed is cash crop not cover crop?
    co2_net = sum(co2_net, na.rm = T),
    increase_lcc_acres = sum(increase_lcc_acres, na.rm = T),
    extra_acres_covered_per_year = sum(extra_acres_covered_per_year, na.rm = T)
  )

```
