---
title: "viz_county_swarm"
output: html_document
---


```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(sf)
library(sysfonts)
library(showtext)
library(ggbeeswarm)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/viz_county_swarm.Rmd")

source(here::here("R/utils.R"))
source(here::here("R/get_scenario_a_data.R"))
source(here::here("R/get_scenario_b_data.R"))
source(here::here("R/get_scenario_c_data.R"))

```


```{r}

params <- yaml::read_yaml(here::here("params.yml"))

baseline_description <- params$descriptions$baseline
scenario_a_description <- params$descriptions$a
scenario_b_description <- params$descriptions$b
scenario_c_description <- params$descriptions$c

dta_baseline <- get_current_crop_data() %>%
  mutate(scenario = baseline_description)

dta_a <- get_scenario_a_data() %>%
  mutate(scenario = scenario_a_description)

dta_b <- get_scenario_b_data() %>%
  mutate(scenario = scenario_b_description)

dta_c <- get_scenario_c_data() %>%
  mutate(scenario = scenario_c_description)

dta <- bind_rows(
  dta_baseline,
  dta_a,
  dta_b,
  dta_c
)

dta$scenario <- factor(dta$scenario, levels = c(
 baseline_description,
  scenario_a_description,
  scenario_b_description,
  scenario_c_description
))

```


```{r}

fig <- dta %>%
  mutate(
    empty_category = ""
  ) %>%
  ggplot( # Format dots
    aes(
      x = co2_total,
      y = empty_category
    )
  ) +
  geom_beeswarm( # offset points within categories to reduce overplotting
    cex = 4,
    side = 0,
    alpha = 0.3,
    size = 3.5,
    color = params$graphics$default_color
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0.02, .02)),
    labels = scales::number_format(scale_cut = scales::cut_short_scale()),
    limits = c(0, NA)
  ) +
  coord_cartesian(clip = "off") +
  theme_cori() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(linewidth = .25, color = "#d0d2ce", linetype = "solid"),
    axis.ticks.length.x = unit(4, "pt"),
    axis.ticks.x = element_line(color = "#d0d2ce", linewidth = .25),
    axis.text.x = element_text(
      color = "black", size = 10,
      margin = margin(t = 2)),
    axis.line.x = element_blank(),
    axis.text.y = element_blank(),
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 20, b = 10),
      size = 10.5
    )
  ) +
  labs(
    title = "CO2 emissions by county",
    subtitle = "For corn grain, soybean, rye, oat, and cover crops",
    x = NULL,
    y = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/swarm_c02_county.png"), chart_height = 8)

```


```{r}

fig <- dta %>%
  mutate(
    empty_category = "",
    pct_cover_crops = cover_crop_acres_planted / viable_cropland
  ) %>%
  ggplot(
    aes(
      x = cover_crop_acres_planted,
      y = empty_category
    )
  ) +
  geom_beeswarm(
    cex = 4,
    side = 0,
    alpha = 0.3,
    size = 3.5,
    color = params$graphics$default_color
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0.02, .02)),
    labels = scales::number_format(scale_cut = scales::cut_short_scale()),
    limits = c(0, NA)
  ) +
  coord_cartesian(clip = "off") +
  theme_cori() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(linewidth = .25, color = "#d0d2ce", linetype = "solid"),
    axis.ticks.length.x = unit(4, "pt"),
    axis.ticks.x = element_line(color = "#d0d2ce", linewidth = .25),
    axis.text.x = element_text(
      color = "black", size = 10,
      margin = margin(t = 2)),
    axis.line.x = element_blank(),
    axis.text.y = element_blank(),
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 20, b = 10),
      size = 10.5
    )
  ) +
  labs(
    title = "Cover crop acres by county",
    subtitle = "For three scenarios",
    x = NULL,
    y = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/swarm_cover_crops_county.png"), chart_height = 8)

```
