---
title: "viz_total_carbon_comparison"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(cartogram)
library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/viz_ia_outcomes_comparison.Rmd")
source(here::here("R/get_current_crop_data.R"))
source(here::here("R/get_scenario_a_data.R"))
source(here::here("R/get_scenario_b_data.R"))
source(here::here("R/get_scenario_c_data.R"))
source(here::here("R/utils.R"))

```

```{r}

params <- yaml::read_yaml(here::here("params.yml"))

baseline_description <- params$descriptions$baseline
scenario_a_description <- params$descriptions$a
scenario_b_description <- params$descriptions$b
scenario_c_description <- params$descriptions$c

dta_baseline <- get_current_crop_data() %>% summarize_county_data() %>%
  mutate(scenario = baseline_description)

dta_a <- get_scenario_a_data() %>% summarize_county_data() %>%
  mutate(scenario = scenario_a_description)

dta_b <- get_scenario_b_data() %>% summarize_county_data() %>%
  mutate(scenario = scenario_b_description)

dta_c <- get_scenario_c_data() %>% summarize_county_data() %>%
  mutate(scenario = scenario_c_description)

co2_baseline <- dta_baseline %>%
  filter(name == "co2_total") %>%
  pull(value) %>%
  max()

dta <- bind_rows(
    dta_a,
    dta_b,
    dta_c
  )

dta$scenario <- factor(dta$scenario, levels = c(
    scenario_a_description,
    scenario_b_description,
    scenario_c_description
  ))

```


```{r}

fig <- dta %>%
  filter(name == "co2_total") %>%
  mutate(
    value = co2_baseline - value
  ) %>%
  ggplot2::ggplot(aes(value, name)) +
  ggplot2::geom_col(fill = params$graphics$default_color) +
  geom_text(
    aes(
      label = paste0(scales::number(
        value,
        accuracy = .11,
        big.mark = ",",
        scale_cut = scales::cut_short_scale()
      ),
      " lbs")
    ),
    fontface = "bold",
    hjust = -.2,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .15))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 6, b = 2),
      size = 10.5
    ),
    axis.text.y = element_blank(),
    axis.line.y.left = element_blank()
  ) +
  ggplot2::labs(
    title = "Reduction in CO2 emissions from baseline",
    subtitle = "For three possible scenarios",
    y = NULL,
    x = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/c02_scenario_comparison.png"), chart_height = 4)

```

```{r}

fig <- dta %>%
  filter(name == "co2_total") %>%
  mutate(
    value = (co2_baseline - value) / co2_baseline
  ) %>%
  ggplot2::ggplot(aes(value, name)) +
  ggplot2::geom_col(fill = params$graphics$default_color) +
  geom_text(
    aes(
      label = scales::percent(
        value,
        accuracy = .1,
        big.mark = ","
      )
    ),
    fontface = "bold",
    hjust = -.2,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .1))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 6, b = 2),
      size = 10.5
    ),
    axis.text.y = element_blank(),
    axis.line.y.left = element_blank()
  ) +
  ggplot2::labs(
    title = "Percent reduction in CO2 emissions from baseline",
    subtitle = "For three possible scenarios",
    y = NULL,
    x = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/c02_pct_scenario_comparison.png"), chart_height = 4)

```

```{r}

fig <- dta %>%
  filter(name == "lcc_acres_harvested") %>%
  ggplot2::ggplot(aes(value, name)) +
  ggplot2::geom_col(fill = params$graphics$default_color) +
  geom_text(
    aes(
      label = paste0(scales::number(
        value,
        accuracy = 1,
        big.mark = ","
        #scale_cut = scales::cut_long_scale()
      ), " acres")
    ),
    fontface = "bold",
    hjust = -.05,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .2))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 6, b = 2),
      size = 10.5
    ),
    axis.text.y = element_blank(),
    axis.line.y.left = element_blank()
  ) +
  ggplot2::labs(
    title = "Increase in low carbon corn acres",
    subtitle = "For three possible scenarios",
    y = NULL,
    x = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/lcc_scenario_comparison.png"), chart_height = 4)

```

```{r}

fig <- dta %>%
  filter(name == "extra_acres_covered_per_year") %>%
  ggplot2::ggplot(aes(value, name)) +
  ggplot2::geom_col(fill = params$graphics$default_color) +
  geom_text(
    aes(
      label = paste0(scales::number(
        value,
        accuracy = 1,
        big.mark = ","
        #scale_cut = scales::cut_long_scale()
      ), " acres")
    ),
    fontface = "bold",
    hjust = -.05,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .2))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 6, b = 2),
      size = 10.5
    ),
    axis.text.y = element_blank(),
    axis.line.y.left = element_blank()
  ) +
  ggplot2::labs(
    title = "Increase in acres covered year round",
    subtitle = "For three possible scenarios",
    y = NULL,
    x = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/yearly_ground_cover_scenario_comparison.png"), chart_height = 4)

```


```{r}

fig <- dta %>%
  filter(name == "pct_cover_crops") %>%
  ggplot2::ggplot(aes(value, name)) +
  ggplot2::geom_col(fill = params$graphics$default_color) +
  geom_text(
    aes(
      label = scales::percent(
        value,
        accuracy = 1,
        big.mark = ","
        #scale_cut = scales::cut_long_scale()
      )
    ),
    fontface = "bold",
    hjust = -.2,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .2))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 6, b = 2),
      size = 10.5
    ),
    axis.text.y = element_blank(),
    axis.line.y.left = element_blank()
  ) +
  ggplot2::labs(
    title = "Percent increase in cover crops",
    subtitle = "For three possible scenarios",
    y = NULL,
    x = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/pct_cover_crops_scenario_comparison.png"), chart_height = 4)

```


```{r}

fig <- dta %>%
  filter(name == "cover_crop_acres_planted") %>%
  ggplot2::ggplot(aes(value, name)) +
  ggplot2::geom_col(fill = params$graphics$default_color) +
  geom_text(
    aes(
      label = paste0(scales::number(
        value,
        accuracy = .1,
        big.mark = ",",
        scale_cut = scales::cut_short_scale()
      ), " acres")
    ),
    fontface = "bold",
    hjust = -.05,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .2))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 6, b = 2),
      size = 10.5
    ),
    axis.text.y = element_blank(),
    axis.line.y.left = element_blank()
  ) +
  ggplot2::labs(
    title = "Increase in cover crop acres",
    subtitle = "For three possible scenarios",
    y = NULL,
    x = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/acres_cover_crops_scenario_comparison.png"), chart_height = 4)

```


```{r}

dta_N <- tibble::tribble(
  ~scenario, ~value, ~name,
  scenario_a_description, 10347712.96, "improved_nitrogen_acres",
  scenario_b_description, 4297959.18, "improved_nitrogen_acres",
  scenario_c_description, 942189.64, "improved_nitrogen_acres"
)

dta_N$scenario <- factor(dta_N$scenario, levels = c(
    scenario_a_description,
    scenario_b_description,
    scenario_c_description
  ))

fig <- dta_N %>%
  ggplot2::ggplot(aes(value, name)) +
  ggplot2::geom_col(fill = params$graphics$default_color) +
  geom_text(
    aes(
      label = paste0(scales::number(
        value,
        accuracy = .1,
        big.mark = ",",
        scale_cut = scales::cut_short_scale()
      ), " acres")
    ),
    fontface = "bold",
    hjust = -.05,
    family = "Lato"
  ) +
  ggplot2::scale_x_continuous(
    labels = NULL,
    expand = expansion(mult = c(0, .2))
  ) +
  theme_cori_horizontal_bars() +
  theme(
    strip.text = element_text(
      family = "Lato",
      hjust = 0, margin = margin(t = 6, b = 2),
      size = 10.5
    ),
    axis.text.y = element_blank(),
    axis.line.y.left = element_blank()
  ) +
  ggplot2::labs(
    title = "Increase in acres with improved nitrogen runoff",
    subtitle = "For three possible scenarios",
    y = NULL,
    x = NULL,
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 1)

save_plot(fig, here::here("export/nitrogen_scenario_comparison.png"), chart_height = 4)

```




