---
title: "viz_county_baseline_maps"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(cori.charts)
library(sf)
library(sysfonts)
library(showtext)

sysfonts::font_add_google("Lato")
font_add(
  "TT Hoves",
  regular = "TypeType - TT Hoves Regular.ttf",
  bold = "TypeType - TT Hoves Bold.ttf",
  italic = "TypeType - TT Hoves Italic.ttf",
  bolditalic = "TypeType - TT Hoves Bold Italic.ttf"
)
showtext_auto()
showtext_opts(dpi = 300)

here::i_am("R/viz_county_baseline_maps.Rmd")

source(here::here("R/utils.R"))
source(here::here("R/get_scenario_a_data.R"))
source(here::here("R/get_scenario_b_data.R"))
source(here::here("R/get_scenario_c_data.R"))

```


```{r}

params <- yaml::read_yaml(here::here("params.yml"))

baseline_description <- params$descriptions$baseline
scenario_a_description <- params$descriptions$a
scenario_b_description <- params$descriptions$b
scenario_c_description <- params$descriptions$c

dta_baseline <- get_current_crop_data() %>%
  mutate(scenario = baseline_description)

dta_a <- get_scenario_a_data() %>%
  mutate(scenario = scenario_a_description)

dta_b <- get_scenario_b_data() %>%
  mutate(scenario = scenario_b_description)

dta_c <- get_scenario_c_data() %>%
  mutate(scenario = scenario_c_description)

dta <- bind_rows(
  dta_baseline,
  dta_a,
  dta_b,
  dta_c
)

dta$scenario <- factor(dta$scenario, levels = c(
 baseline_description,
  scenario_a_description,
  scenario_b_description,
  scenario_c_description
))

```


```{r}

baseline_green_share <- dta_baseline %>% 
  summarize_county_data() %>%
  tidyr::pivot_wider(
    names_from = "name", 
    values_from = "value"
  ) %>%
  mutate(
    green_total = cover_crop_acres_planted + oats_acres_harvested + rye_acres_harvested + lcc_acres_harvested,
    pct_green_crops = green_total / viable_cropland
  ) %>%
  pull(pct_green_crops) %>%
  max()

chrt_dta <- dta %>%
  mutate(
    green_total = cover_crop_acres_planted + oats_acres_harvested + rye_acres_harvested + lcc_acres_harvested,
    pct_green_crops = green_total / viable_cropland
  ) %>%
  left_join(
    .,
    ia_counties <- tigris::counties(state = "IA", cb = TRUE, year = 2021),
    by = c("geoid_co" = "GEOID")
  ) %>%
  sf::st_as_sf()

```


```{r}

fig <- chrt_dta %>%
  # filter(scenario == baseline_description) %>%
  ggplot() +
  geom_sf(data = chrt_dta, fill = "#d0d2ce", color = "#d0d2ce", linewidth = 0.01) +
  geom_sf(aes(fill = pct_green_crops), color = "#d0d2ce", linewidth = 0.01) +

  scale_fill_gradientn(
    colours = c("#7B3F00","#FBF8E9","#00835D"),
    values = scales::rescale(c(0, baseline_green_share, max(chrt_dta$pct_green_crops))),
    guide = "colorbar",
    limits=c(0, NA),
    breaks = c(baseline_green_share, .25, .5, .75),
    labels = c("Current avg. share (4.3%)", "25%", "50%", "75%")
  ) +
  theme_cori_map() +
  theme(
    legend.key.width = unit(60, "pt"),
    legend.margin = margin(t = 5)
  ) +
  labs(
    title = "Share of green crops by county",
    subtitle = "Green crops are the aggregation of rye, oats, low carbon corn, and cover crops",
    caption = "Source: 2017 Census of Agriculture"
  ) +
  facet_wrap(~scenario, ncol = 2)

save_plot(fig, here::here("export/green_crop_county_maps.png"), chart_height = 8.8, chart_width = 10)

```


